--- #YAML:1.0
name:               Xymon-Server-History
version:            0.18
abstract:           Return a hash of Xymon events history
author:
    - David Peters (davidp@electronf.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:      0.01
    Test::Simple:    0.44
    Time::Business:  0.13
    Time::Local:     0.01
    Xymon::Server:   0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
